application: jamur2nes2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: feedreader.ui.main.application

- url: /ui
  static_dir: feedreader/ui/static

- url: /api/feed.*
  script: feedreader.api.feed.application

- url: /api/user.*
  script: feedreader.api.user.application

- url: /api/entry.*
  script: feedreader.api.entry.application

- url: /async/.*
  script: feedreader.async.fetcher.application
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
